[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker working_server:app"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"